"""Create users table

Revision ID: c4b0503b3d9f
Revises: 9cec06c4707d
Create Date: 2026-10-02 21:30:46.031685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b0503b3d9f'
down_revision: Union[str, Sequence[str], None] = '9cec06c4707d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('parent_sport_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sports_id'), 'sports', ['id'], unique=False)
    op.add_column('groups', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('groups', sa.Column('name', sa.String(), nullable=False))
    op.add_column('groups', sa.Column('description', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('sports_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_comments_id'), table_name='groups')
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.drop_constraint(op.f('groups_user_id_fkey'), 'groups', type_='foreignkey')
    op.drop_constraint(op.f('groups_tea_id_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'sports', ['sports_id'], ['id'])
    op.create_foreign_key(None, 'groups', 'users', ['owner_id'], ['id'])
    op.drop_column('groups', 'tea_id')
    op.drop_column('groups', 'content')
    op.drop_column('groups', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('tea_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'groups', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_tea_id_fkey'), 'groups', 'teas', ['tea_id'], ['id'])
    op.create_foreign_key(op.f('groups_user_id_fkey'), 'groups', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.create_index(op.f('ix_comments_id'), 'groups', ['id'], unique=False)
    op.drop_column('groups', 'sports_id')
    op.drop_column('groups', 'photo_url')
    op.drop_column('groups', 'description')
    op.drop_column('groups', 'name')
    op.drop_column('groups', 'owner_id')
    op.drop_index(op.f('ix_sports_id'), table_name='sports')
    op.drop_table('sports')
    # ### end Alembic commands ###
