"""sports

Revision ID: d6aa2130eb1d
Revises: c4b0503b3d9f
Create Date: 2026-10-02 22:21:32.288394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6aa2130eb1d'
down_revision: Union[str, Sequence[str], None] = 'c4b0503b3d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sports_parent_sport_id_fkey'), 'sports', type_='foreignkey')
    op.drop_column('sports', 'parent_sport_id')
    op.drop_column('sports', 'description')
    op.drop_column('sports', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sports', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sports', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sports', sa.Column('parent_sport_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sports_parent_sport_id_fkey'), 'sports', 'sports', ['parent_sport_id'], ['id'])
    # ### end Alembic commands ###
