"""rooms

Revision ID: ff68e239fa3a
Revises: 8de830259a14
Create Date: 2026-10-03 21:09:39.328083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff68e239fa3a'
down_revision: Union[str, Sequence[str], None] = '8de830259a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(), server_default='beginners', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('slot_layout', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('visibility', sa.String(), server_default='public', nullable=False),
    sa.Column('admission_policy', sa.String(), server_default='approval', nullable=False),
    sa.Column('public_area', sa.String(), nullable=False),
    sa.Column('venue_details', sa.Text(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('pace_notes', sa.String(), nullable=True),
    sa.Column('route_notes', sa.Text(), nullable=True),
    sa.Column('host_generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("admission_policy IN ('approval', 'open')", name='ck_rooms_admission_policy'),
    sa.CheckConstraint("difficulty IN ('beginners', 'medium', 'advenced')", name='ck_rooms_difficulty'),
    sa.CheckConstraint("status IN ('open', 'started', 'completed', 'cancelled')", name='ck_rooms_status'),
    sa.CheckConstraint("visibility != 'group' OR group_id IS NOT NULL", name='ck_rooms_group_visibility_needs_group'),
    sa.CheckConstraint("visibility IN ('public', 'private', 'group')", name='ck_rooms_visibility'),
    sa.CheckConstraint('capacity > 0', name='ck_rooms_capacity_positive'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_rooms_end_after_start'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.add_column('sports', sa.Column('formats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sports', 'formats')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
